name: CI

on:
  push:
    branches:
      - feature/*

jobs:
  Autofix:
    name: Autofix CI
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies & Autofix
      id: npm-install-autofix
      run: |
        npm_output=$(npm install)
        sanitized_output=$(echo "$npm_output" | jq -Rs .)
        API_TOKEN=${{ secrets.HF_API_TOKEN }}
        MODEL="gpt2"
        # INPUT_TEXT="Summarize the following npm install output in less than 20 words: $sanitized_output"
        INPUT_TEXT="Hi are you good?"
        RESPONSE=$(curl -s -X POST "https://api-inference.huggingface.co/models/$MODEL" \
            -H "Authorization: Bearer $API_TOKEN" \
            -H "Content-Type: application/json" \
            -d "{\"inputs\": $sanitized_output}")
        
        summary=$(echo $RESPONSE | jq -r '.[0].generated_text')
        echo "Summary: $summary"
