name: Node.js CI with Docker Deployment

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  Node_CI_Deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3

      - name: Install dependencies
        run: npm install

      - name: Check for vulnerabilities
        run: npm audit
      
      - name: Deploy to Docker
        if: ${{ github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main' && github.event.pull_request.head.ref == 'development' }}
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker build -t projectx_backend . 
          docker tag projectx_backend ${{ secrets.DOCKER_USERNAME }}/projectx_backend
          docker push ${{ secrets.DOCKER_USERNAME }}/projectx_backend

